# NumPy Avanzado — actividad ejecutada

En este notebook se practican arreglos de NumPy, sus propiedades principales y la generación de matrices aleatorias.

In [1]:
import numpy as np
import random

np.random.seed(42)
random.seed(42)

In [2]:
lista = [[1, 2, 3, 4],
         [3, 4, 5, 6],
         [5, 6, 7, 8]]

array_2d = np.array(lista, dtype='float')
array_2d

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [3]:
print("Tipo:", type(array_2d))
print("Dimensiones:", array_2d.ndim)
print("Shape:", array_2d.shape)
print("Size:", array_2d.size)
print("dtype:", array_2d.dtype)

Tipo: <class 'numpy.ndarray'>
Dimensiones: 2
Shape: (3, 4)
Size: 12
dtype: float64


## Operaciones vectorizadas

Una ventaja de `ndarray` es que una operación puede aplicarse a todos los elementos sin recorrerlos manualmente.

In [4]:
array_2d + 2

array([[ 3.,  4.,  5.,  6.],
       [ 5.,  6.,  7.,  8.],
       [ 7.,  8.,  9., 10.]])

## Generación de matrices aleatorias con Python

In [5]:
def generar_matriz(N):
    matriz = []
    for i in range(N):
        fila = []
        for j in range(N):
            fila.append(random.randint(1, 9))
        matriz.append(fila)
    return matriz

def imprimir_matriz(matriz):
    for fila in matriz:
        print(' '.join(f'{elemento:2}' for elemento in fila))

m_5 = generar_matriz(5)
imprimir_matriz(m_5)

 2  1  5  4  4
 3  2  9  2  7
 1  1  2  4  4
 9  1  9  4  9
 7  4  8  5  1


In [6]:
m_10 = generar_matriz(10)
m_20 = generar_matriz(20)

print("Matriz 5x5:", len(m_5), "filas x", len(m_5[0]), "columnas")
print("Matriz 10x10:", len(m_10), "filas x", len(m_10[0]), "columnas")
print("Matriz 20x20:", len(m_20), "filas x", len(m_20[0]), "columnas")

Matriz 5x5: 5 filas x 5 columnas
Matriz 10x10: 10 filas x 10 columnas
Matriz 20x20: 20 filas x 20 columnas


## La misma idea usando NumPy

In [7]:
matriz_numpy = np.random.randint(1, 10, size=(5, 5))
matriz_numpy

array([[7, 4, 8, 5, 7],
       [3, 7, 8, 5, 4],
       [8, 8, 3, 6, 5],
       [2, 8, 6, 2, 5],
       [1, 6, 9, 1, 3]])

### Conclusión

NumPy permite representar datos con arreglos multidimensionales y consultar fácilmente su dimensión, forma, tamaño y tipo de dato. Además, las operaciones vectorizadas simplifican los cálculos sobre matrices.